parameters:
    code_iso.france: fr
    code_iso.allemagne: de
    code_iso.angleterre: gb-eng
    code_iso.argentine: ar
    code_iso.australie: au
    code_iso.autriche: at
    code_iso.belgique: be
    code_iso.canada: ca
    code_iso.chine: cn
    code_iso.cuba: cu
    code_iso.danemark: dk
    code_iso.ecosse: gb-sct
    code_iso.espagne: es
    code_iso.hollande: nl
    code_iso.inde: in
    code_iso.irelande: ie
    code_iso.italie: it
    code_iso.jamaique: jm
    code_iso.japon: jp
    code_iso.maroc: ma
    code_iso.mexique: mx
    code_iso.norvege: no
    code_iso.nouvelle_zelande: nz
    code_iso.pays_de_galles: gb-wls
    code_iso.pologne: pl
    code_iso.portugal: pt
    code_iso.republique_tcheque: cz
    code_iso.sri_lanka: lk
    code_iso.suede: se
    code_iso.usa: us
    code_iso.vietnam: vn
