# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        public: false
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }
